component_depth: 1
languages:
- java
exclude:
- ./accessories/.*
- ./accessories/plugins/.*
- ./accessories/plugins/dialogs/.*
- ./accessories/plugins/flash/.*
- ./accessories/plugins/icons/.*
- ./accessories/plugins/time/.*
- ./accessories/plugins/util/.*
- ./accessories/plugins/util/html/.*
- ./accessories/plugins/util/window/.*
- ./accessories/plugins/util/xslt/.*
- ./bin/.*
- ./bin/classes/.*
- ./bin/classes/accessories/.*
- ./bin/classes/accessories/plugins/.*
- ./bin/classes/accessories/plugins/dialogs/.*
- ./bin/classes/accessories/plugins/flash/.*
- ./bin/classes/accessories/plugins/icons/.*
- ./bin/classes/accessories/plugins/time/.*
- ./bin/classes/accessories/plugins/util/.*
- ./bin/classes/accessories/plugins/util/html/.*
- ./bin/classes/accessories/plugins/util/window/.*
- ./bin/classes/accessories/plugins/util/xslt/.*
- ./bin/classes/de/.*
- ./bin/classes/de/foltin/.*
- ./bin/classes/doc/.*
- ./bin/classes/doc/development/.*
- ./bin/classes/doc/development/icons/.*
- ./bin/classes/freemind/.*
- ./bin/classes/freemind/common/.*
- ./bin/classes/freemind/controller/.*
- ./bin/classes/freemind/controller/filter/.*
- ./bin/classes/freemind/controller/filter/condition/.*
- ./bin/classes/freemind/controller/filter/util/.*
- ./bin/classes/freemind/controller/printpreview/.*
- ./bin/classes/freemind/extensions/.*
- ./bin/classes/freemind/main/.*
- ./bin/classes/freemind/modes/.*
- ./bin/classes/freemind/modes/attributes/.*
- ./bin/classes/freemind/modes/browsemode/.*
- ./bin/classes/freemind/modes/common/.*
- ./bin/classes/freemind/modes/common/actions/.*
- ./bin/classes/freemind/modes/common/dialogs/.*
- ./bin/classes/freemind/modes/common/listeners/.*
- ./bin/classes/freemind/modes/common/plugins/.*
- ./bin/classes/freemind/modes/filemode/.*
- ./bin/classes/freemind/modes/mindmapmode/.*
- ./bin/classes/freemind/modes/mindmapmode/actions/.*
- ./bin/classes/freemind/modes/mindmapmode/actions/xml/.*
- ./bin/classes/freemind/modes/mindmapmode/attributeactors/.*
- ./bin/classes/freemind/modes/mindmapmode/dialogs/.*
- ./bin/classes/freemind/modes/mindmapmode/hooks/.*
- ./bin/classes/freemind/modes/mindmapmode/listeners/.*
- ./bin/classes/freemind/modes/schememode/.*
- ./bin/classes/freemind/modes/viewmodes/.*
- ./bin/classes/freemind/preferences/.*
- ./bin/classes/freemind/preferences/layout/.*
- ./bin/classes/freemind/view/.*
- ./bin/classes/freemind/view/mindmapview/.*
- ./bin/classes/freemind/view/mindmapview/attributeview/.*
- ./bin/classes/html/.*
- ./bin/classes/images/.*
- ./bin/classes/images/icons/.*
- ./bin/classes/lib/.*
- ./bin/classes/lib/SimplyHTML/.*
- ./bin/classes/lib/jibx/.*
- ./bin/classes/plugins/.*
- ./bin/classes/plugins/collaboration/.*
- ./bin/classes/plugins/collaboration/database/.*
- ./bin/classes/plugins/help/.*
- ./bin/classes/plugins/help/doc/.*
- ./bin/classes/plugins/help/doc/JavaHelpSearch/.*
- ./bin/classes/plugins/latex/.*
- ./bin/classes/plugins/script/.*
- ./bin/classes/plugins/svg/.*
- ./bin/classes/tests/.*
- ./bin/classes/tests/freemind/.*
- ./bin/classes/tests/freemind/findreplace/.*
- ./de/.*
- ./de/foltin/.*
- ./doc/.*
- ./doc/development/.*
- ./doc/development/icons/.*
- ./freemind/.*
- ./freemind/common/.*
- ./freemind/controller/.*
- ./freemind/controller/filter/.*
- ./freemind/controller/filter/condition/.*
- ./freemind/controller/filter/util/.*
- ./freemind/controller/printpreview/.*
- ./freemind/extensions/.*
- ./freemind/main/.*
- ./freemind/modes/.*
- ./freemind/modes/attributes/.*
- ./freemind/modes/browsemode/.*
- ./freemind/modes/common/.*
- ./freemind/modes/common/actions/.*
- ./freemind/modes/common/dialogs/.*
- ./freemind/modes/common/listeners/.*
- ./freemind/modes/common/plugins/.*
- ./freemind/modes/filemode/.*
- ./freemind/modes/mindmapmode/.*
- ./freemind/modes/mindmapmode/actions/.*
- ./freemind/modes/mindmapmode/actions/xml/.*
- ./freemind/modes/mindmapmode/attributeactors/.*
- ./freemind/modes/mindmapmode/dialogs/.*
- ./freemind/modes/mindmapmode/hooks/.*
- ./freemind/modes/mindmapmode/listeners/.*
- ./freemind/modes/schememode/.*
- ./freemind/modes/viewmodes/.*
- ./freemind/preferences/.*
- ./freemind/preferences/layout/.*
- ./freemind/view/.*
- ./freemind/view/mindmapview/.*
- ./freemind/view/mindmapview/attributeview/.*
- ./html/.*
- ./images/.*
- ./images/icons/.*
- ./lib/.*
- ./lib/SimplyHTML/.*
- ./lib/jibx/.*
- ./plugins/.*
- ./plugins/collaboration/.*
- ./plugins/collaboration/database/.*
- ./plugins/collaboration/jabber/.*
- ./plugins/collaboration/jabber/mindmap/.*
- ./plugins/collaboration/jabber/view/.*
- ./plugins/help/.*
- ./plugins/help/doc/.*
- ./plugins/help/doc/JavaHelpSearch/.*
- ./plugins/latex/.*
- ./plugins/script/.*
- ./plugins/svg/.*
- ./tests/.*
- ./tests/freemind/.*
- ./tests/freemind/findreplace/.*
- ./windows-launcher/.*
